export const ERROR_CODE = {
  // Room errors
  ROOM_NOT_FOUND: 'ROOM_NOT_FOUND',
  ROOM_FULL: 'ROOM_FULL',
  ROOM_EXPIRED: 'ROOM_EXPIRED',

  // Auth errors
  INVALID_TOKEN: 'INVALID_TOKEN',
  INVALID_PASSWORD: 'INVALID_PASSWORD',
  UNAUTHORIZED: 'UNAUTHORIZED',
  PASSWORD_REQUIRED: 'PASSWORD_REQUIRED',
  PASSWORD_UNCORRECT: 'PASSWORD_UNCORRECT',
  NICKNAME_REQUIRED: 'NICKNAME_REQUIRED',
  TOKEN_ROOM_MISMATCH: 'TOKEN_ROOM_MISMATCH',
  PERMISSION_DENIED: 'PERMISSION_DENIED',

  // Validation errors
  INVALID_INPUT: 'INVALID_INPUT',
  INVALID_ROOM_CODE: 'INVALID_ROOM_CODE',
  INVALID_NICKNAME: 'INVALID_NICKNAME',

  // Participant errors
  PT_NOT_FOUND: 'PT_NOT_FOUND',
  NOT_HOST: 'NOT_HOST',

  // Host claim errors
  CLAIM_ALREADY_PENDING: 'CLAIM_ALREADY_PENDING',
  HOST_NOT_FOUND: 'HOST_NOT_FOUND',

  // File errors
  FILE_NOT_FOUND: 'FILE_NOT_FOUND',
  INVALID_FILENAME: 'INVALID_FILENAME',
  DUPLICATE_FILENAME: 'DUPLICATE_FILENAME',

  // Code execution errors
  CODE_EXECUTION_FAILED: 'CODE_EXECUTION_FAILED',
  CODE_EXECUTION_SERVICE_UNAVAILABLE: 'CODE_EXECUTION_SERVICE_UNAVAILABLE',
  CODE_EXECUTION_INVALID_CONFIG: 'CODE_EXECUTION_INVALID_CONFIG',
  CODE_EXECUTION_ALREADY_INITIALIZED: 'CODE_EXECUTION_ALREADY_INITIALIZED',
  CODE_EXECUTION_INIT_TIMEOUT: 'CODE_EXECUTION_INIT_TIMEOUT',
  CODE_EXECUTION_ERROR: 'CODE_EXECUTION_ERROR',
  CODE_EXECUTION_NOT_INITIALIZED: 'CODE_EXECUTION_NOT_INITIALIZED',
  CODE_EXECUTION_INVALID_STREAM: 'CODE_EXECUTION_INVALID_STREAM',
  CODE_EXECUTION_INVALID_SIGNAL: 'CODE_EXECUTION_INVALID_SIGNAL',
  INVALID_LANGUAGE: 'INVALID_LANGUAGE',
  INVALID_LANGUAGE_VERSION: 'INVALID_LANGUAGE_VERSION',

  // Rate limit errors
  TOO_MANY_REQUESTS: 'TOO_MANY_REQUESTS',

  // Room limit errors
  ROOM_LIMIT_EXCEEDED: 'ROOM_LIMIT_EXCEEDED',

  // Server errors
  SERVER_ERROR: 'SERVER_ERROR',
} as const;
