export const ERROR_CODE = {
  // Room errors
  ROOM_NOT_FOUND: 'ROOM_NOT_FOUND',
  ROOM_FULL: 'ROOM_FULL',
  ROOM_EXPIRED: 'ROOM_EXPIRED',

  // Auth errors
  INVALID_TOKEN: 'INVALID_TOKEN',
  INVALID_PASSWORD: 'INVALID_PASSWORD',
  UNAUTHORIZED: 'UNAUTHORIZED',
  PASSWORD_REQUIRED: 'PASSWORD_REQUIRED',
  PASSWORD_UNCORRECT: 'PASSWORD_UNCORRECT',
  NICKNAME_REQUIRED: 'NICKNAME_REQUIRED',
  TOKEN_ROOM_MISMATCH: 'TOKEN_ROOM_MISMATCH',
  PERMISSION_DENIED: 'PERMISSION_DENIED',

  // Validation errors
  INVALID_INPUT: 'INVALID_INPUT',
  INVALID_ROOM_CODE: 'INVALID_ROOM_CODE',
  INVALID_NICKNAME: 'INVALID_NICKNAME',

  // Participant errors
  PT_NOT_FOUND: 'PT_NOT_FOUND',
  NOT_HOST: 'NOT_HOST',

  // Host claim errors
  CLAIM_ALREADY_PENDING: 'CLAIM_ALREADY_PENDING',
  HOST_NOT_FOUND: 'HOST_NOT_FOUND',

  // File errors
  FILE_NOT_FOUND: 'FILE_NOT_FOUND',
  INVALID_FILENAME: 'INVALID_FILENAME',
  DUPLICATE_FILENAME: 'DUPLICATE_FILENAME',

  // Rate limit errors
  TOO_MANY_REQUESTS: 'TOO_MANY_REQUESTS',

  // Server errors
  SERVER_ERROR: 'SERVER_ERROR',
} as const;
